//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamoCRM.Web.Mvc.WsCRMSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsCRMSoap.WsCRMSoap")]
    public interface WsCRMSoap {
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeInterviewInfo", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse ChangeInterviewInfo(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeInterviewInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse> ChangeInterviewInfoAsync(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelInterview", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse CancelInterview(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelInterview", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse> CancelInterviewAsync(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTopicaMark", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse UpdateTopicaMark(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTopicaMark", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse> UpdateTopicaMarkAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_duplicate", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse Check_duplicate(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check_duplicate", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse> Check_duplicateAsync(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest request);
        
        // CODEGEN: Generating message contract since element name str_contactid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ContactID", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse Get_ContactID(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_ContactID", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse> Get_ContactIDAsync(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response UpdateSB100(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response> UpdateSB100Async(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100_topica", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse UpdateSB100_topica(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100_topica", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse> UpdateSB100_topicaAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcountCasec", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse UpdateAcountCasec(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcountCasec", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse> UpdateAcountCasecAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTTPhongVan", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse UpdateTTPhongVan(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTTPhongVan", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse> UpdateTTPhongVanAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeInterviewInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeInterviewInfo", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequestBody Body;
        
        public ChangeInterviewInfoRequest() {
        }
        
        public ChangeInterviewInfoRequest(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeInterviewInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public ChangeInterviewInfoRequestBody() {
        }
        
        public ChangeInterviewInfoRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeInterviewInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeInterviewInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponseBody Body;
        
        public ChangeInterviewInfoResponse() {
        }
        
        public ChangeInterviewInfoResponse(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeInterviewInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChangeInterviewInfoResult;
        
        public ChangeInterviewInfoResponseBody() {
        }
        
        public ChangeInterviewInfoResponseBody(string ChangeInterviewInfoResult) {
            this.ChangeInterviewInfoResult = ChangeInterviewInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelInterviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelInterview", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequestBody Body;
        
        public CancelInterviewRequest() {
        }
        
        public CancelInterviewRequest(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelInterviewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public CancelInterviewRequestBody() {
        }
        
        public CancelInterviewRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelInterviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelInterviewResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponseBody Body;
        
        public CancelInterviewResponse() {
        }
        
        public CancelInterviewResponse(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelInterviewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelInterviewResult;
        
        public CancelInterviewResponseBody() {
        }
        
        public CancelInterviewResponseBody(string CancelInterviewResult) {
            this.CancelInterviewResult = CancelInterviewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTopicaMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTopicaMark", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequestBody Body;
        
        public UpdateTopicaMarkRequest() {
        }
        
        public UpdateTopicaMarkRequest(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTopicaMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateTopicaMarkRequestBody() {
        }
        
        public UpdateTopicaMarkRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTopicaMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTopicaMarkResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponseBody Body;
        
        public UpdateTopicaMarkResponse() {
        }
        
        public UpdateTopicaMarkResponse(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTopicaMarkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateTopicaMarkResult;
        
        public UpdateTopicaMarkResponseBody() {
        }
        
        public UpdateTopicaMarkResponseBody(string UpdateTopicaMarkResult) {
            this.UpdateTopicaMarkResult = UpdateTopicaMarkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_duplicateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_duplicate", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequestBody Body;
        
        public Check_duplicateRequest() {
        }
        
        public Check_duplicateRequest(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_duplicateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public Check_duplicateRequestBody() {
        }
        
        public Check_duplicateRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Check_duplicateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check_duplicateResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponseBody Body;
        
        public Check_duplicateResponse() {
        }
        
        public Check_duplicateResponse(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Check_duplicateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Check_duplicateResult;
        
        public Check_duplicateResponseBody() {
        }
        
        public Check_duplicateResponseBody(string Check_duplicateResult) {
            this.Check_duplicateResult = Check_duplicateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_ContactIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_ContactID", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequestBody Body;
        
        public Get_ContactIDRequest() {
        }
        
        public Get_ContactIDRequest(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_ContactIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_contactid;
        
        public Get_ContactIDRequestBody() {
        }
        
        public Get_ContactIDRequestBody(string str_contactid) {
            this.str_contactid = str_contactid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_ContactIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_ContactIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponseBody Body;
        
        public Get_ContactIDResponse() {
        }
        
        public Get_ContactIDResponse(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_ContactIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Get_ContactIDResult;
        
        public Get_ContactIDResponseBody() {
        }
        
        public Get_ContactIDResponseBody(string Get_ContactIDResult) {
            this.Get_ContactIDResult = Get_ContactIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100RequestBody Body;
        
        public UpdateSB100Request() {
        }
        
        public UpdateSB100Request(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateSB100RequestBody() {
        }
        
        public UpdateSB100RequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100Response", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100ResponseBody Body;
        
        public UpdateSB100Response() {
        }
        
        public UpdateSB100Response(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSB100Result;
        
        public UpdateSB100ResponseBody() {
        }
        
        public UpdateSB100ResponseBody(string UpdateSB100Result) {
            this.UpdateSB100Result = UpdateSB100Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100_topicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100_topica", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequestBody Body;
        
        public UpdateSB100_topicaRequest() {
        }
        
        public UpdateSB100_topicaRequest(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100_topicaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateSB100_topicaRequestBody() {
        }
        
        public UpdateSB100_topicaRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100_topicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100_topicaResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponseBody Body;
        
        public UpdateSB100_topicaResponse() {
        }
        
        public UpdateSB100_topicaResponse(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100_topicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSB100_topicaResult;
        
        public UpdateSB100_topicaResponseBody() {
        }
        
        public UpdateSB100_topicaResponseBody(string UpdateSB100_topicaResult) {
            this.UpdateSB100_topicaResult = UpdateSB100_topicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAcountCasecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAcountCasec", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequestBody Body;
        
        public UpdateAcountCasecRequest() {
        }
        
        public UpdateAcountCasecRequest(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAcountCasecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateAcountCasecRequestBody() {
        }
        
        public UpdateAcountCasecRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAcountCasecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAcountCasecResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponseBody Body;
        
        public UpdateAcountCasecResponse() {
        }
        
        public UpdateAcountCasecResponse(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAcountCasecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAcountCasecResult;
        
        public UpdateAcountCasecResponseBody() {
        }
        
        public UpdateAcountCasecResponseBody(string UpdateAcountCasecResult) {
            this.UpdateAcountCasecResult = UpdateAcountCasecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTTPhongVanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTTPhongVan", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequestBody Body;
        
        public UpdateTTPhongVanRequest() {
        }
        
        public UpdateTTPhongVanRequest(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTTPhongVanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateTTPhongVanRequestBody() {
        }
        
        public UpdateTTPhongVanRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTTPhongVanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTTPhongVanResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponseBody Body;
        
        public UpdateTTPhongVanResponse() {
        }
        
        public UpdateTTPhongVanResponse(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTTPhongVanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateTTPhongVanResult;
        
        public UpdateTTPhongVanResponseBody() {
        }
        
        public UpdateTTPhongVanResponseBody(string UpdateTTPhongVanResult) {
            this.UpdateTTPhongVanResult = UpdateTTPhongVanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsCRMSoapChannel : TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsCRMSoapClient : System.ServiceModel.ClientBase<TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap>, TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap {
        
        public WsCRMSoapClient() {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCRMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.ChangeInterviewInfo(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest request) {
            return base.Channel.ChangeInterviewInfo(request);
        }
        
        public string ChangeInterviewInfo(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).ChangeInterviewInfo(inValue);
            return retVal.Body.ChangeInterviewInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.ChangeInterviewInfoAsync(TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest request) {
            return base.Channel.ChangeInterviewInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoResponse> ChangeInterviewInfoAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.ChangeInterviewInfoRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).ChangeInterviewInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.CancelInterview(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest request) {
            return base.Channel.CancelInterview(request);
        }
        
        public string CancelInterview(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).CancelInterview(inValue);
            return retVal.Body.CancelInterviewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.CancelInterviewAsync(TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest request) {
            return base.Channel.CancelInterviewAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewResponse> CancelInterviewAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.CancelInterviewRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).CancelInterviewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateTopicaMark(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest request) {
            return base.Channel.UpdateTopicaMark(request);
        }
        
        public string UpdateTopicaMark(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateTopicaMark(inValue);
            return retVal.Body.UpdateTopicaMarkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateTopicaMarkAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest request) {
            return base.Channel.UpdateTopicaMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkResponse> UpdateTopicaMarkAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTopicaMarkRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateTopicaMarkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.Check_duplicate(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest request) {
            return base.Channel.Check_duplicate(request);
        }
        
        public string Check_duplicate(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).Check_duplicate(inValue);
            return retVal.Body.Check_duplicateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.Check_duplicateAsync(TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest request) {
            return base.Channel.Check_duplicateAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateResponse> Check_duplicateAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.Check_duplicateRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).Check_duplicateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.Get_ContactID(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest request) {
            return base.Channel.Get_ContactID(request);
        }
        
        public string Get_ContactID(string str_contactid) {
            TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequestBody();
            inValue.Body.str_contactid = str_contactid;
            TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).Get_ContactID(inValue);
            return retVal.Body.Get_ContactIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.Get_ContactIDAsync(TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest request) {
            return base.Channel.Get_ContactIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDResponse> Get_ContactIDAsync(string str_contactid) {
            TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.Get_ContactIDRequestBody();
            inValue.Body.str_contactid = str_contactid;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).Get_ContactIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateSB100(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request request) {
            return base.Channel.UpdateSB100(request);
        }
        
        public string UpdateSB100(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100RequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateSB100(inValue);
            return retVal.Body.UpdateSB100Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateSB100Async(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request request) {
            return base.Channel.UpdateSB100Async(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Response> UpdateSB100Async(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100Request();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100RequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateSB100Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateSB100_topica(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest request) {
            return base.Channel.UpdateSB100_topica(request);
        }
        
        public string UpdateSB100_topica(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateSB100_topica(inValue);
            return retVal.Body.UpdateSB100_topicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateSB100_topicaAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest request) {
            return base.Channel.UpdateSB100_topicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaResponse> UpdateSB100_topicaAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateSB100_topicaRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateSB100_topicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateAcountCasec(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest request) {
            return base.Channel.UpdateAcountCasec(request);
        }
        
        public string UpdateAcountCasec(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateAcountCasec(inValue);
            return retVal.Body.UpdateAcountCasecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateAcountCasecAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest request) {
            return base.Channel.UpdateAcountCasecAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecResponse> UpdateAcountCasecAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateAcountCasecRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateAcountCasecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateTTPhongVan(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest request) {
            return base.Channel.UpdateTTPhongVan(request);
        }
        
        public string UpdateTTPhongVan(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse retVal = ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateTTPhongVan(inValue);
            return retVal.Body.UpdateTTPhongVanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse> TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap.UpdateTTPhongVanAsync(TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest request) {
            return base.Channel.UpdateTTPhongVanAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanResponse> UpdateTTPhongVanAsync(string information) {
            TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest inValue = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsCRMSoap.UpdateTTPhongVanRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsCRMSoap.WsCRMSoap)(this)).UpdateTTPhongVanAsync(inValue);
        }
    }
}
