//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamoCRM.Web.Mvc.WsOfCasec {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsOfCasec.WsCRMSoap")]
    public interface WsCRMSoap {
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeInterviewInfo", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse ChangeInterviewInfo(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeInterviewInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse> ChangeInterviewInfoAsync(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelInterview", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse CancelInterview(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelInterview", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse> CancelInterviewAsync(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response UpdateSB100(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSB100", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response> UpdateSB100Async(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcountCasec", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse UpdateAcountCasec(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcountCasec", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse> UpdateAcountCasecAsync(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest request);
        
        // CODEGEN: Generating message contract since element name information from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTTPhongVan", ReplyAction="*")]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse UpdateTTPhongVan(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTTPhongVan", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse> UpdateTTPhongVanAsync(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeInterviewInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeInterviewInfo", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequestBody Body;
        
        public ChangeInterviewInfoRequest() {
        }
        
        public ChangeInterviewInfoRequest(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeInterviewInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public ChangeInterviewInfoRequestBody() {
        }
        
        public ChangeInterviewInfoRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeInterviewInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeInterviewInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponseBody Body;
        
        public ChangeInterviewInfoResponse() {
        }
        
        public ChangeInterviewInfoResponse(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeInterviewInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChangeInterviewInfoResult;
        
        public ChangeInterviewInfoResponseBody() {
        }
        
        public ChangeInterviewInfoResponseBody(string ChangeInterviewInfoResult) {
            this.ChangeInterviewInfoResult = ChangeInterviewInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelInterviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelInterview", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequestBody Body;
        
        public CancelInterviewRequest() {
        }
        
        public CancelInterviewRequest(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelInterviewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public CancelInterviewRequestBody() {
        }
        
        public CancelInterviewRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelInterviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelInterviewResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponseBody Body;
        
        public CancelInterviewResponse() {
        }
        
        public CancelInterviewResponse(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelInterviewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelInterviewResult;
        
        public CancelInterviewResponseBody() {
        }
        
        public CancelInterviewResponseBody(string CancelInterviewResult) {
            this.CancelInterviewResult = CancelInterviewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100RequestBody Body;
        
        public UpdateSB100Request() {
        }
        
        public UpdateSB100Request(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateSB100RequestBody() {
        }
        
        public UpdateSB100RequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSB100Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSB100Response", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100ResponseBody Body;
        
        public UpdateSB100Response() {
        }
        
        public UpdateSB100Response(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSB100ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSB100Result;
        
        public UpdateSB100ResponseBody() {
        }
        
        public UpdateSB100ResponseBody(string UpdateSB100Result) {
            this.UpdateSB100Result = UpdateSB100Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAcountCasecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAcountCasec", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequestBody Body;
        
        public UpdateAcountCasecRequest() {
        }
        
        public UpdateAcountCasecRequest(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAcountCasecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateAcountCasecRequestBody() {
        }
        
        public UpdateAcountCasecRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAcountCasecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAcountCasecResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponseBody Body;
        
        public UpdateAcountCasecResponse() {
        }
        
        public UpdateAcountCasecResponse(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAcountCasecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAcountCasecResult;
        
        public UpdateAcountCasecResponseBody() {
        }
        
        public UpdateAcountCasecResponseBody(string UpdateAcountCasecResult) {
            this.UpdateAcountCasecResult = UpdateAcountCasecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTTPhongVanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTTPhongVan", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequestBody Body;
        
        public UpdateTTPhongVanRequest() {
        }
        
        public UpdateTTPhongVanRequest(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTTPhongVanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string information;
        
        public UpdateTTPhongVanRequestBody() {
        }
        
        public UpdateTTPhongVanRequestBody(string information) {
            this.information = information;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTTPhongVanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTTPhongVanResponse", Namespace="http://tempuri.org/", Order=0)]
        public TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponseBody Body;
        
        public UpdateTTPhongVanResponse() {
        }
        
        public UpdateTTPhongVanResponse(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTTPhongVanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateTTPhongVanResult;
        
        public UpdateTTPhongVanResponseBody() {
        }
        
        public UpdateTTPhongVanResponseBody(string UpdateTTPhongVanResult) {
            this.UpdateTTPhongVanResult = UpdateTTPhongVanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsCRMSoapChannel : TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsCRMSoapClient : System.ServiceModel.ClientBase<TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap>, TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap {
        
        public WsCRMSoapClient() {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCRMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCRMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.ChangeInterviewInfo(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest request) {
            return base.Channel.ChangeInterviewInfo(request);
        }
        
        public string ChangeInterviewInfo(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse retVal = ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).ChangeInterviewInfo(inValue);
            return retVal.Body.ChangeInterviewInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse> TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.ChangeInterviewInfoAsync(TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest request) {
            return base.Channel.ChangeInterviewInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoResponse> ChangeInterviewInfoAsync(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.ChangeInterviewInfoRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).ChangeInterviewInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.CancelInterview(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest request) {
            return base.Channel.CancelInterview(request);
        }
        
        public string CancelInterview(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse retVal = ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).CancelInterview(inValue);
            return retVal.Body.CancelInterviewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse> TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.CancelInterviewAsync(TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest request) {
            return base.Channel.CancelInterviewAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewResponse> CancelInterviewAsync(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.CancelInterviewRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).CancelInterviewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateSB100(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request request) {
            return base.Channel.UpdateSB100(request);
        }
        
        public string UpdateSB100(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100RequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response retVal = ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateSB100(inValue);
            return retVal.Body.UpdateSB100Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response> TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateSB100Async(TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request request) {
            return base.Channel.UpdateSB100Async(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Response> UpdateSB100Async(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100Request();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateSB100RequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateSB100Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateAcountCasec(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest request) {
            return base.Channel.UpdateAcountCasec(request);
        }
        
        public string UpdateAcountCasec(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse retVal = ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateAcountCasec(inValue);
            return retVal.Body.UpdateAcountCasecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse> TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateAcountCasecAsync(TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest request) {
            return base.Channel.UpdateAcountCasecAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecResponse> UpdateAcountCasecAsync(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateAcountCasecRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateAcountCasecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateTTPhongVan(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest request) {
            return base.Channel.UpdateTTPhongVan(request);
        }
        
        public string UpdateTTPhongVan(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequestBody();
            inValue.Body.information = information;
            TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse retVal = ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateTTPhongVan(inValue);
            return retVal.Body.UpdateTTPhongVanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse> TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap.UpdateTTPhongVanAsync(TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest request) {
            return base.Channel.UpdateTTPhongVanAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanResponse> UpdateTTPhongVanAsync(string information) {
            TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest inValue = new TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequest();
            inValue.Body = new TamoCRM.Web.Mvc.WsOfCasec.UpdateTTPhongVanRequestBody();
            inValue.Body.information = information;
            return ((TamoCRM.Web.Mvc.WsOfCasec.WsCRMSoap)(this)).UpdateTTPhongVanAsync(inValue);
        }
    }
}
