//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace TamoCRM.Window.TestService.ServiceMissCall {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceCRMSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceCRM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MissCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncomingOperationCompleted;
        
        private System.Threading.SendOrPostCallback TCLCallInfoUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateConectStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCloseCampainOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceCRM() {
            this.Url = global::TamoCRM.Window.TestService.Properties.Settings.Default.TamoCRM_Window_TestService_ServiceMissCall_ServiceCRM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MissCallCompletedEventHandler MissCallCompleted;
        
        /// <remarks/>
        public event IncomingCompletedEventHandler IncomingCompleted;
        
        /// <remarks/>
        public event TCLCallInfoUpdateCompletedEventHandler TCLCallInfoUpdateCompleted;
        
        /// <remarks/>
        public event UpdateConectStatusCompletedEventHandler UpdateConectStatusCompleted;
        
        /// <remarks/>
        public event UpdateCloseCampainCompletedEventHandler UpdateCloseCampainCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MissCall", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMissCall MissCall(string infomation) {
            object[] results = this.Invoke("MissCall", new object[] {
                        infomation});
            return ((ResultMissCall)(results[0]));
        }
        
        /// <remarks/>
        public void MissCallAsync(string infomation) {
            this.MissCallAsync(infomation, null);
        }
        
        /// <remarks/>
        public void MissCallAsync(string infomation, object userState) {
            if ((this.MissCallOperationCompleted == null)) {
                this.MissCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMissCallOperationCompleted);
            }
            this.InvokeAsync("MissCall", new object[] {
                        infomation}, this.MissCallOperationCompleted, userState);
        }
        
        private void OnMissCallOperationCompleted(object arg) {
            if ((this.MissCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MissCallCompleted(this, new MissCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Incoming", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMissCall Incoming(string infomation) {
            object[] results = this.Invoke("Incoming", new object[] {
                        infomation});
            return ((ResultMissCall)(results[0]));
        }
        
        /// <remarks/>
        public void IncomingAsync(string infomation) {
            this.IncomingAsync(infomation, null);
        }
        
        /// <remarks/>
        public void IncomingAsync(string infomation, object userState) {
            if ((this.IncomingOperationCompleted == null)) {
                this.IncomingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncomingOperationCompleted);
            }
            this.InvokeAsync("Incoming", new object[] {
                        infomation}, this.IncomingOperationCompleted, userState);
        }
        
        private void OnIncomingOperationCompleted(object arg) {
            if ((this.IncomingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncomingCompleted(this, new IncomingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TCLCallInfoUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result TCLCallInfoUpdate(string infomation) {
            object[] results = this.Invoke("TCLCallInfoUpdate", new object[] {
                        infomation});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void TCLCallInfoUpdateAsync(string infomation) {
            this.TCLCallInfoUpdateAsync(infomation, null);
        }
        
        /// <remarks/>
        public void TCLCallInfoUpdateAsync(string infomation, object userState) {
            if ((this.TCLCallInfoUpdateOperationCompleted == null)) {
                this.TCLCallInfoUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCLCallInfoUpdateOperationCompleted);
            }
            this.InvokeAsync("TCLCallInfoUpdate", new object[] {
                        infomation}, this.TCLCallInfoUpdateOperationCompleted, userState);
        }
        
        private void OnTCLCallInfoUpdateOperationCompleted(object arg) {
            if ((this.TCLCallInfoUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TCLCallInfoUpdateCompleted(this, new TCLCallInfoUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateConectStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result UpdateConectStatus(string infomation) {
            object[] results = this.Invoke("UpdateConectStatus", new object[] {
                        infomation});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateConectStatusAsync(string infomation) {
            this.UpdateConectStatusAsync(infomation, null);
        }
        
        /// <remarks/>
        public void UpdateConectStatusAsync(string infomation, object userState) {
            if ((this.UpdateConectStatusOperationCompleted == null)) {
                this.UpdateConectStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateConectStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateConectStatus", new object[] {
                        infomation}, this.UpdateConectStatusOperationCompleted, userState);
        }
        
        private void OnUpdateConectStatusOperationCompleted(object arg) {
            if ((this.UpdateConectStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateConectStatusCompleted(this, new UpdateConectStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCloseCampain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result UpdateCloseCampain(string infomation) {
            object[] results = this.Invoke("UpdateCloseCampain", new object[] {
                        infomation});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCloseCampainAsync(string infomation) {
            this.UpdateCloseCampainAsync(infomation, null);
        }
        
        /// <remarks/>
        public void UpdateCloseCampainAsync(string infomation, object userState) {
            if ((this.UpdateCloseCampainOperationCompleted == null)) {
                this.UpdateCloseCampainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCloseCampainOperationCompleted);
            }
            this.InvokeAsync("UpdateCloseCampain", new object[] {
                        infomation}, this.UpdateCloseCampainOperationCompleted, userState);
        }
        
        private void OnUpdateCloseCampainOperationCompleted(object arg) {
            if ((this.UpdateCloseCampainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCloseCampainCompleted(this, new UpdateCloseCampainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultMissCall {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private int codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void MissCallCompletedEventHandler(object sender, MissCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MissCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MissCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMissCall Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMissCall)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IncomingCompletedEventHandler(object sender, IncomingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncomingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncomingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMissCall Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMissCall)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TCLCallInfoUpdateCompletedEventHandler(object sender, TCLCallInfoUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TCLCallInfoUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TCLCallInfoUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateConectStatusCompletedEventHandler(object sender, UpdateConectStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateConectStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateConectStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateCloseCampainCompletedEventHandler(object sender, UpdateCloseCampainCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCloseCampainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCloseCampainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591