//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamoCRM.Call.WsAutoDialService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DefaultNamespace", ConfigurationName="WsAutoDialService.TPCAutoDial")]
    public interface TPCAutoDial {
        
        // CODEGEN: Generating message contract since element name input from namespace http://DefaultNamespace is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        TamoCRM.Call.WsAutoDialService.processMsgResponse processMsg(TamoCRM.Call.WsAutoDialService.processMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TamoCRM.Call.WsAutoDialService.processMsgResponse> processMsgAsync(TamoCRM.Call.WsAutoDialService.processMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processMsg", Namespace="http://DefaultNamespace", Order=0)]
        public TamoCRM.Call.WsAutoDialService.processMsgRequestBody Body;
        
        public processMsgRequest() {
        }
        
        public processMsgRequest(TamoCRM.Call.WsAutoDialService.processMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class processMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public processMsgRequestBody() {
        }
        
        public processMsgRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processMsgResponse", Namespace="http://DefaultNamespace", Order=0)]
        public TamoCRM.Call.WsAutoDialService.processMsgResponseBody Body;
        
        public processMsgResponse() {
        }
        
        public processMsgResponse(TamoCRM.Call.WsAutoDialService.processMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class processMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processMsgReturn;
        
        public processMsgResponseBody() {
        }
        
        public processMsgResponseBody(string processMsgReturn) {
            this.processMsgReturn = processMsgReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TPCAutoDialChannel : TamoCRM.Call.WsAutoDialService.TPCAutoDial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPCAutoDialClient : System.ServiceModel.ClientBase<TamoCRM.Call.WsAutoDialService.TPCAutoDial>, TamoCRM.Call.WsAutoDialService.TPCAutoDial {
        
        public TPCAutoDialClient() {
        }
        
        public TPCAutoDialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPCAutoDialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPCAutoDialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPCAutoDialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TamoCRM.Call.WsAutoDialService.processMsgResponse TamoCRM.Call.WsAutoDialService.TPCAutoDial.processMsg(TamoCRM.Call.WsAutoDialService.processMsgRequest request) {
            return base.Channel.processMsg(request);
        }
        
        public string processMsg(string input) {
            TamoCRM.Call.WsAutoDialService.processMsgRequest inValue = new TamoCRM.Call.WsAutoDialService.processMsgRequest();
            inValue.Body = new TamoCRM.Call.WsAutoDialService.processMsgRequestBody();
            inValue.Body.input = input;
            TamoCRM.Call.WsAutoDialService.processMsgResponse retVal = ((TamoCRM.Call.WsAutoDialService.TPCAutoDial)(this)).processMsg(inValue);
            return retVal.Body.processMsgReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TamoCRM.Call.WsAutoDialService.processMsgResponse> TamoCRM.Call.WsAutoDialService.TPCAutoDial.processMsgAsync(TamoCRM.Call.WsAutoDialService.processMsgRequest request) {
            return base.Channel.processMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<TamoCRM.Call.WsAutoDialService.processMsgResponse> processMsgAsync(string input) {
            TamoCRM.Call.WsAutoDialService.processMsgRequest inValue = new TamoCRM.Call.WsAutoDialService.processMsgRequest();
            inValue.Body = new TamoCRM.Call.WsAutoDialService.processMsgRequestBody();
            inValue.Body.input = input;
            return ((TamoCRM.Call.WsAutoDialService.TPCAutoDial)(this)).processMsgAsync(inValue);
        }
    }
}
